CARTI_SLANG = [":( 💕\n", "🍄", " lit **!++", "+:) love !", "*+!:) !!\n", "\nxo !", "* +", "\n +", "++**", " slatt", ".$", ".. ", "++*", "^\n", "++!", ":)", ":^/", "!", ":-)", "*", "!+", "++", "_"]
CARTI_EMOJIS = ["🦋", "❤️", "🦇", "💕", "💔", "🖤", "🍄"]
CARTI_QUOTES = [
    "I don't care what nobody say. I'ma be me.",
    "I'm ahead of my time.",
    "I've been on opium for the last 10 days.",
    "I don't even listen to rap.",
    "I don't talk. I don't like to talk.",
    "I just want to make people feel good.",
    "I'm about making history.",
    "I'm all about the music.",
    "I want my music to be next level.",
    "I'm trying to change the world.",
    "I be in my own world.",
    "I'm always in the studio.",
    "I'm never not working.",
    "I can't be stopped.",
    "I like making music that makes people feel good.",
    "I feel like I'm a rockstar.",
    "I always had the dream to be on stage.",
    "I was born to be a star.",
    "I always knew I was going to make it.",
    "I never gave up.",
    "I'm all about the vibes.",
    "I'm just trying to make a name for myself.",
    "I'm all about positivity."
]
CARTI_ADLIBS = [
    "*+!",
    "What!",
    "Bee!",
    "Hey!",
    "Slatt!",
    "Yuh!",
    "holup"
    "Vamp!",
    "Bih!",
    "Codeine",
    "Woah!",
    "Uh!",
    "Homidide!",
    "Aeeayaahhh!"
    "Hey!",
    "Pew!",
    "Woo!",
    "Huh?",
    "No!",
    "Buh buh buh!",
    "Playboi",
    "Ok!",
    "Reggie!",
    "Hold up!",
    "Cash!",
    "Jumpin'!",
    "On God!",
    "Let's go!",
    "pussy bitch",
    "Chain gang!",
    "Money!",
    "Woke up!",
    "Racks!",
    "Wait!",
    "Stop!",
    "Where?",
    "How?",
    "Pop pop pop!",
    "Pull up!",
]