import random

CARTI_TWEETS = [
                #old tweets
                "vote obama",
                "my white friends tried to teach me to paly beer pong.. .lol i just smoke the reefer mon",
                "Im a God, im no longer a black man,",
                "So I might dye my hair, like red, \nbecause I want my teachers to think \nima some sick rebel kid trying to get a\n hustle, lol #wtf was that",
                "im out ..wheres my mom?",
                "Fck man I finna smash on this 20 piece mcnuggets",
                "so how about me and this beautiful \nyoung lady are going to see harry \npotter, and i havent even seen the \n1st, one",
                "You teenage girls with all this makeup, \n y ... Your beautiful",
                "In this bitch watching pokemon! . My ash",
                "Which one of you hoes tryna to make \n a movie",
                "me and jay finna fuck a hoe in a\n amusement park", 
                "ima stay single for the rest of my life \ncuh, money first, hoes will come",
                "i want 2 have sex right now",
                "Haven't had sex in a while :(",
                "all i want for my birthday is , sex \nmoney drugs and a new skateboard\n lol",
                "I want a bitch that knows when all the \njordans come out",
                "my girl is not my girlfriend, but if u see \nme with another bitchm shell check me \n like shes my girlfriend, swag",
                #music era
                "love all my supporters  it’s time",
                "Hello    Twitter",
                "Cult",
                "HARDcore",
                "Narcissist",
                "DONDA > YE >",
                #red era
                "i miss uuuuuuu",
                "🤪",
                "Lol DrUNk . ❤️  . SKY Video > OUT nOW",
                "bE yOU",
                "heY i miss U !",
                "bE Y0u . i love You",
                "!!!!! wTF . wE r # 1 > mY fANs . >",
                "rIP mF dOOM ! wTF",
                "wE pARTY HaRD 2 niGHT >",
                "OMFg oMg 0mG > r3D r3d REd > .",
                "sTop brEATh1NG. hA hA hA! -kING vAMP",
                "wHicH viDEO nEXT ??? TALk 2 mE >",
                "dELuxE oTW . > yEs",
                "tALk 2 me > WAT sOng . d0 u neeD oN deLuxE >> ??????",
                "i kANT wAIt 2 PeFORM dis ALbum . >oMG > MOSH pITttttttttttttttt >>>>",
                "KID CUDi N MEH . W3NT rOCksTAR 2 oHh YA ! >  M3tamorphosis >>> 💋",
                "eVRY boDy rUN oUt tH3 houSE RN ! > gO",
                "kAYne wESt i loV3 u BoY ! > 💋",
                "kING VAMP L0v3 U !\n\n mERRY VAmPMAS . w3 Did it . \n 💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋💋",
                "wE pARTY HaRD 2 niGHT >",
                "iT bEEN 2 YEArS wTF . >",
                "12/25 > 💋",
                "oMG wtF i cAN nOT wAIT >",
                "lOv3 U .",
                "kID cUDI oN kID cUDI  > 🧛🏿‍♂️🧛🏿‍♂️>",
                "oMG ! FucKkkk . w3 did iT . iM CRYIN",
                "G0000000000000",
                "AHhhhhhhhhhhhhhhhhh\nI t0LD U ! I L0v3 u\n PRE 0RDeR NOW ",
                "d0nT sL33p",
                "mY b3sT w0rk YET .",
                "i lovvvve uuuuu .",
                "r3d > teAM > RT",
                "oMG",
                "s0 happY",
                "❤️",
                "i hAv3 a gift 4 u :0",
                "i hAv3 da m0st loyAL fanS. EVr .",
                "hEY",
                "TEAM RED",
                "HeY",
                "ᶦ ᵐᶦˢˢ               ᶦ ᵐᶦˢˢ   \n            ᶦ ᵐᶦˢˢ ᶦ ᵐᶦˢˢ \n             ᶦ ᵐᶦˢˢ\nᶦ ᵐᶦˢˢ     yAL <3    ᶦ ᵐᶦˢˢ\nᶦ ᵐᶦˢˢ                  ᶦ ᵐᶦˢˢ\nᶦ ᵐᶦˢˢ                ᶦ ᵐᶦˢˢ            ᶦ ᵐᶦˢˢ",
                "i lov3  yAL  .",
                "ed .",
                "d0nt di3 bout dat 4 letter 💋💕word  xoxo 😊 ",
                "😂",
                "onyx .",
                "i dNt ev3n kno when i did dat verse . 💋 hard",
                "IM gOiNG INSANE",
                "Call Jesus  !",
                "LOVE ME NOW NOT WH3N IM DEAD",
                "i love u . RT",
                "wow !",
                "we bACk!!!!",
                "HeY",
                "OUt of MY boDY ! WHOLE TAPE",
                #pre-wlr
                "Red is MY fav album . ❤️ of mine .",
                "HEy . <3",
                "rEd .",
                ". MoNDaY",
                "@ meh ! out now !",
                "no sleep . X",
                "4vr . Lit",
                "i Kant wait .",
                "I Kan NOt Beef Ah bit Ya",
                "wHO THiS is???? playboi cahti",
                #post die-lit
                "i win k ?",
                "Love u !",
                "!! \n@GUNNERSELLWHITE\nhappy birthday",
                "FREE NUDY ! TF !",
                "HA ! AMAZING ! *",
                "love like you’ve never been hurt ! *",
                "FY!!",
                "NO SLEEP !TODAY IS THE DAY ! +:) iM BRINGING CRAZY ENERGY EVERY SHOW.  WAKE TF UP . x",
                "○        BABYMAMA\nく|)へ\n    〉 \n ￣￣┗┓              \n 　 　   ┗┓　     ヾ○ｼ\n  　　        ┗┓   ヘ/ 　 　 \n 　                 ┗┓ノ \n　 　 　 　 　    ┗┓ ME",
                "love / is high school all over again ! *",
                "i put all my opps in  Ah Group Chat and told them *link up ! i want all da smoke ! _SLATT ! Fuc it !",
                "4U !! 🖤 DIE LIT *+ _ SLATT !",
                "*he has to be da happiest kidd ever *! +:) live it up kid !! ♥️ thx .",
                "FOSHO ! *  MOOD ! *",
                "🖤🤦‍♀️",
                "* breathing is so difficult for meh @ da moment! Literally scared to fall asleep on my back . i have da worst case of asthma. N never knew til today . to all my fans who suffer from asthma! I’m with u n #we as a whole must stay strong *",
                "JULY 24* CARTI TOUR 2018 \nBEGINS !!!  +:) EXTRA PSYCH OUT!!!",
                "wow *+:) i can’t wait for this fuckin tour^ to begin *+  :) xo! - giving mY ALL EVERY SHOW  *+ ON FREDO ! ",
                "*  * \nCARTI ALBUM @ 12* +am\nok !",
                "love hurts  ** + new * carti\n ** \n@trvisXX\n ** - went brazy\n\n+:) Love You *+  ",
                "💔💔💔",
                "the biggest inspiration * R.I.P.",
                "Uzi Carti * Carti Uzi * Tape ... loading"
                ]

def handle_tweet(message):
    if (len(message.split()) != 1):
        return "`tweet` takes no args!"
    else:
        return random.choice(CARTI_TWEETS)